name: smoke-test
on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    smoke-tests:
        runs-on: ubuntu-latest
        container:
            image: node:23.3.0-bullseye  # Exact version to match smokeTests.sh requirement
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            NODE_OPTIONS: --no-node-snapshot --experimental-loader=ts-node/esm/transpile-only  # Configure Node.js for ESM and native modules
            DISABLE_PLUGINS: true  # Disable plugins during smoke tests
            TS_NODE_TRANSPILE_ONLY: true  # Speed up ts-node by skipping type checking
            NODE_NO_WARNINGS: 1  # Suppress experimental warnings
        steps:
            - uses: actions/checkout@v4

            - name: Cache pnpm
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.pnpm-store
                      **/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9.15.0

            - name: Run smoke tests
              run: pnpm run smokeTests
